=== sandhyapaudel18/XML/first.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT college (name,address,faculty+)>
<!ELEMENT faculty (name,num,sub)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT sub (#PCDATA)>

=== sandhyapaudel18/XML/first.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE college SYSTEM "./first.dtd"> -->

<college xmlns:xsi="https://www.w3.org.com"
xmln>
    
    <name>BUTWAL KALIKA CAMPUS</name>
    <address>Butwal</address>


    <faculty xmlns="https://www.example1.com">
        <name>BCA</name>
        <num>100</num>
        <sub>five</sub>
    </faculty>

    <faculty xmlns="https://www.example2.com"> 
        <name>BBS</name>
        <num>300</num>
        <sub>six</sub>
    </faculty>

    <faculty xmlns="https://www.example3.com">
        <name>BSW</name>
        <num>50</num>
        <sub>seven</sub>
    </faculty>


</college>
